# Generated by Django 4.2 on 2023-04-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fact_multi',
            new_name='factmulti',
        ),
    ]
